### ISSUE TITLE
engage with outdoor groups in PNW

### ISSUE THREAD

**Issue by aaarendt** [aaarendt/nasacso-webapp#11]
Write up a blurb with links to MtnHub and CSO. Groups include:

* [Turns all year](http://www.turns-all-year.com/)
* [Cascade climbers](http://cascadeclimbers.com/) 
* [Open snow](https://opensnow.com/) avalanche centers

**Comment by dfhkvs** [comment]
I posted to TAY. 

Also, I reached out to NWAC and to COAA (Central Oregon Avalanche Association). Stay tuned on that.

We just missed the NSAW Workshop in Seattle (October, 2017) which is too bad. We should have thought of trying to make a presentation there.
